ci/ga: Add pypy3.10 and pypy3.11 jobs
Restrict max pypy heap size to 3GB.
Bump test timeout to 360 min.

Signed-off-by: Jan Vesely <jan.vesely@rutgers.edu>

fixup pypy jobs

diff --git a/.github/actions/install-pnl/action.yml b/.github/actions/install-pnl/action.yml
--- a/.github/actions/install-pnl/action.yml
+++ b/.github/actions/install-pnl/action.yml
@@ -24,10 +24,22 @@ runs:
       # Composited actions can't use step conditionals.
       run: |
         case "$RUNNER_OS" in
-          macOS*) brew install graphviz ;;
-          Linux*) sudo apt-get update && sudo apt-get install -y --no-install-recommends graphviz ;;
-          Windows*) choco install --no-progress -y graphviz --version=2.38.0.20190211 ;;
-          *) echo "Unsupported OS"; exit 1 ;;
+          macOS*)
+            brew install graphviz ;;
+          Linux*)
+            sudo apt update
+            if ! apt-cache search llvm${LLVM_SUFFIX} | grep llvm${LLVM_SUFFIX} ; then
+              sudo apt-get install -y --no-install-recommends wget gpg-agent
+              LLVM_VERSION=${LLVM_SUFFIX:1}
+              wget -O - https://apt.llvm.org/llvm.sh | sudo bash -s -- ${LLVM_VERSION}
+            fi
+
+            sudo apt-get install -y --no-install-recommends graphviz build-essential pkg-config gfortran llvm${LLVM_SUFFIX}-dev libfreetype6-dev libjpeg-dev libopenblas-dev zlib1g-dev
+            echo "CMAKE_PREFIX_PATH=$(llvm-config${LLVM_SUFFIX} --prefix)" >> $GITHUB_ENV ;;
+          Windows*)
+            choco install --no-progress -y graphviz --version=2.38.0.20190211 ;;
+          *)
+            echo "Unsupported OS"; exit 1 ;;
         esac
 
     - name: Setup Python venv
@@ -44,9 +56,9 @@ runs:
         echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
         echo "$PYTHON_LOC" >> $GITHUB_PATH
 
-    - name: Update pip and wheel
+    - name: Update pip, wheel, and cython
       shell: bash
-      run: python -m pip install --upgrade pip wheel
+      run: python -m pip install --upgrade pip wheel 'cython<3'
 
     - name: Install updated package
       if: ${{ startsWith(github.head_ref, 'dependabot/pip') && matrix.pnl-version != 'base' && matrix.version-restrict == '' }}
@@ -87,7 +99,7 @@ runs:
     - name: Python dependencies
       shell: bash
       run: |
-        pip install ${{ steps.dist.outputs.wheel }}[${{ inputs.features }}] -c broken_trans_deps.txt
+        pip install ${{ steps.dist.outputs.wheel }}[${{ inputs.features }}] -c broken_trans_deps.txt --use-pep517
       env:
         # Setting CXXFLAGS works around a missing include that breaks the build
         # of onnx-1/17.0 on recent gcc/clang compilers.
@@ -101,6 +113,13 @@ runs:
         # This should be removed once onnx wheels for Python 3.13 are available.
         # Note that $TEMP is only used to set pip's build location on Windows.
         TEMP: ${{ runner.temp }}
+        LLVM_CONFIG: llvm-config${{ env.LLVM_SUFFIX }}
+
+        # grpcio sdist package bundles cythonized files. This can be overridden
+        # by the variable below set to '1'. However, newer grpcio versions fail
+        # to build if this is set in isolated build.
+        # see https://github.com/grpc/grpc/issues/39487
+        GRPC_PYTHON_BUILD_WITH_CYTHON: 0
 
     - name: Cleanup old wheels
       shell: bash
